name: Merge Dependabot pull requests

on:
  pull_request:
    types: [opened]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check build status
        uses: actions/github-script@v4
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: statuses } = await github.request('GET /repos/{owner}/{repo}/commits/{sha}/statuses', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
            });
            const buildStatuses = statuses.filter(s => s.context.startsWith('ci/'));
            const failingBuildStatuses = buildStatuses.filter(s => s.state !== 'success');
            if (failingBuildStatuses.length > 0) {
              core.info(`Build is failing with statuses: ${failingBuildStatuses.map(s => `${s.context}=${s.state}`).join(', ')}`);
              core.setFailed('Build is failing');
              return;
            }
            core.info('Build is passing');
            const { data: pr } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            if (pr.mergeable !== true) {
              core.setFailed('Pull request is not mergeable');
              return;
            }
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash',
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
